---
title: "climate_data"
author: "Alex Milward"
date: "10/19/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(janitor)

```

Read in data

```{r}
#parse out year, month, day

 climate <- read.csv("climate.csv") %>%
   clean_names() 
#   mutate(year = lubridate::year(date),
#          month = lubridate::month(date),
#          day = lubridate::day(date)
#   drop_na()

climate_year <- climate %>% 
  mutate(year = lubridate::year(date)) %>% 
  group_by(year) %>% 
  summarize(mean_temp_max = mean(tmax),
            mean_temp_min = mean(tmin),
            mean_temp = (mean_temp_max + mean_temp_min)/2) %>% 
  drop_na()
  

# climate <- read.csv("climate.csv") %>% 
#   clean_names() %>% 
#   mutate(mo_y_day = lubridate::parse_date_time(date, "myd"))

#summarize annually

climate_annual <- climate %>% 
  group_by(month = floor_date(as.Date(date), "month")) %>% 
  summarize(total_precip = sum(prcp),
            mean_temp_max = mean(tmax),
            mean_temp_min = mean(tmin),
            mean_temp = (mean_temp_max + mean_temp_min)/2) %>% 
  mutate(year = year(month)) %>% 
  drop_na()

climate_average <- climate_year %>% 
  summarize(meantemp = mean(mean_temp))

#graph
precip_graph <- ggplot(data = climate_annual, aes(y = total_precip, x = month)) +
  geom_line(color = "blue") +
 # scale_y_continuous(expand = c(0,0)) +
 # scale_x_continuous(expand = c(0,0)) +
  labs(title = "Monthly precipitation from 1992 - 2020",
         x = "year",
         y = "monthly precipiation (inches)") +
  theme_bw()

precip_graph

temp_graph <- ggplot(data = climate_annual) +
   geom_line(aes(y = mean_temp, x = month), size = 1) +
   geom_line(aes(y = mean_temp_max, x = month), color = "red", linetype = "dashed") +
   geom_line(aes(y = mean_temp_min, x = month), color = "blue", linetype = "dashed") +
   scale_y_continuous(expand = c(0,10)) +
  theme_light() +
  labs(x = "year",
       y = "temperature (Fahrenheit)",
       title = "Monthly temperature 1992-2020",
       subtitle = "Maximum, daily average, and minimum") +
  geom_abline(intercept = 63.37, slope = 0, linetype = "dashed", color = "black", x = (0:2020))

 temp_graph
 
 
 
 




```
testing to add minor change
